arrowParens: avoid
bracketSpacing: true
jsxBracketSameLine: true
jsxSingleQuote: true
printWidth: 80
quoteProps: 'as-needed'
semi: true
singleQuote: true
tabWidth: 2
trailingComma: 'none'
useTabs: false
